In [3]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LogisticRegression

df = pd.read_excel("loan.xlsx")
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 429 entries, 0 to 428
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   Sex              429 non-null    object 
 1   Age              429 non-null    float64
 2   Time_at_address  429 non-null    float64
 3   Res_status       429 non-null    object 
 4   Telephone        429 non-null    object 
 5   Occupation       429 non-null    object 
 6   Job_status       429 non-null    object 
 7   Time_employed    429 non-null    int64  
 8   Time_bank        429 non-null    int64  
 9   Liab_ref         429 non-null    object 
 10  Acc_ref          429 non-null    object 
 11  Home_Expn        429 non-null    int64  
 12  Balance          429 non-null    int64  
 13  Decision         429 non-null    object 
dtypes: float64(2), int64(4), object(8)
memory usage: 33.6+ KB


In [5]:
x = df[df.columns[df.columns != 'Decision']]
y = df.Decision

#Checking data
df.head()

Sex        Age  Time_at_address Res_status  Telephone Occupation Job_status  \
0   M  50.750000            0.585      owner      given  unemploye  unemploye   
1   M  19.670000           10.000       rent  not_given   labourer  governmen   
2   F  52.830002           15.000      owner      given  creative_  private_s   
3   M  22.670000            2.540       rent  not_given  creative_  governmen   
4   M  29.250000           13.000      owner      given     driver  governmen   

   Time_employed  Time_bank Liab_ref Acc_ref  Home_Expn  Balance Decision  
0              0          0        f   given        145        0   reject  
1              0          0        t   given        140        0   reject  
2              5         14        f   given          0     2200   accept  
3              2          0        f   given          0        0   accept  
4              0          0        f   given        228        0   reject

In [6]:
%pip install category_encoders

In [7]:
import category_encoders as ce
encoder = ce.OneHotEncoder(cols=['Sex','Res_status','Telephone','Occupation','Job_status','Liab_ref','Acc_ref','Decision'], use_cat_names=True)

In [9]:
from sklearn.model_selection import train_test_split

train_encoded = encoder.fit_transform(df)
train_encoded.head()

Sex_M  Sex_F        Age  Time_at_address  Res_status_owner  \
0      1      0  50.750000            0.585                 1   
1      1      0  19.670000           10.000                 0   
2      0      1  52.830002           15.000                 1   
3      1      0  22.670000            2.540                 0   
4      1      0  29.250000           13.000                 1   

   Res_status_rent  Telephone_given  Telephone_not_given  \
0                0                1                    0   
1                1                0                    1   
2                0                1                    0   
3                1                0                    1   
4                0                1                    0   

   Occupation_unemploye  Occupation_labourer  ...  Time_employed  Time_bank  \
0                     1                    0  ...              0          0   
1                     0                    1  ...              0          0   
2                     0                    0  ...              5         14   
3                     0                    0  ...              2          0   
4                     0                    0  ...              0          0   

   Liab_ref_f  Liab_ref_t  Acc_ref_given  Acc_ref_oth_inst_  Home_Expn  \
0           1           0              1                  0        145   
1           0           1              1                  0        140   
2           1           0              1                  0          0   
3           1           0              1                  0          0   
4           1           0              1                  0        228   

   Balance  Decision_reject  Decision_accept  
0        0                1                0  
1        0                1                0  
2     2200                0                1  
3        0                0                1  
4        0                1                0  

[5 rows x 37 columns]

In [18]:
x1=train_encoded[['Age','Time_at_address','Home_Expn','Balance','Time_bank','Time_employed']]
y1=train_encoded[['Decision_accept']]

model=LogisticRegression(solver='lbfgs', max_iter=3000)
model.fit(x1,y1.values.ravel())

LogisticRegression(max_iter=3000)

In [20]:
model.intercept_

array([-1.21257531])

In [21]:
model.coef_

array([[-0.00319337,  0.00343342, -0.00084811,  0.00037844,  0.33846284,
         0.26526688]])

In [22]:
 model.predict_proba(x1)

array([[8.16918248e-01, 1.83081752e-01],
       [7.95725583e-01, 2.04274417e-01],
       [3.80511480e-03, 9.96194885e-01],
       [6.78244167e-01, 3.21755833e-01],
       [8.10723172e-01, 1.89276828e-01],
       [7.33475130e-01, 2.66524870e-01],
       [7.30018626e-01, 2.69981374e-01],
       [6.58144863e-01, 3.41855137e-01],
       [7.57658585e-01, 2.42341415e-01],
       [7.59501923e-01, 2.40498077e-01],
       [4.66585054e-02, 9.53341495e-01],
       [8.00492060e-01, 1.99507940e-01],
       [4.97026868e-01, 5.02973132e-01],
       [8.14549143e-01, 1.85450857e-01],
       [3.66970118e-03, 9.96330299e-01],
       [7.40554841e-01, 2.59445159e-01],
       [4.28159949e-01, 5.71840051e-01],
       [8.06537953e-01, 1.93462047e-01],
       [8.02996537e-01, 1.97003463e-01],
       [5.96242102e-02, 9.40375790e-01],
       [3.81189649e-01, 6.18810351e-01],
       [8.07691436e-01, 1.92308564e-01],
       [5.95216819e-01, 4.04783181e-01],
       [6.10225256e-01, 3.89774744e-01],
       [3.669740

In [23]:
model.predict(x1)

array([0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0,
       0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1,
       0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1,
       0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0,
       0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1,
       1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1,
       0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0,
       1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1,
       0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1,

In [24]:
model.score(x1, y1)

0.7715617715617715